---
- name: "This is a simple ansible that will echo what ever that is sent as input argument"
  hosts: localhost
  vars:
    GivenMessage : "{{ EchoText }}"
  tasks:
    - name: "Task that will echo the given argument"
      debug:
        msg: "GivenMessage variable has value of {{ GivenMessage }}"
